--liquibase formatted sql

--changeset mmichalenok:1
CREATE SCHEMA IF NOT EXISTS app
    AUTHORIZATION postgres;

--changeset mmichalenok:2

CREATE TABLE IF NOT EXISTS app.patients
(
    id bigint GENERATED BY DEFAULT AS IDENTITY  ,
    lastname VARCHAR(30) NOT NULL,
    firstname VARCHAR(20) NOT NULL,
    surname VARCHAR(30) NOT NULL,
    address VARCHAR(80) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    medical_card_number VARCHAR(30) NOT NULL,
    dt_created timestamp without time zone NOT NULL,
    dt_updated timestamp without time zone NOT NULL,
    CONSTRAINT patients_pkey PRIMARY KEY (id)
);
--rollback DROP TABLE app.patients;

--changeset mmichalenok:3
CREATE TABLE IF NOT EXISTS app.employees
(
    id bigint GENERATED BY DEFAULT AS IDENTITY  ,
    dt_created timestamp without time zone,
    dt_updated timestamp without time zone,
    department VARCHAR(60) NOT NULL,
    position VARCHAR(60) NOT NULL,
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(30) NOT NULL,
    surname VARCHAR(30) NOT NULL,
    CONSTRAINT employees_pkey PRIMARY KEY (id)
);
--rollback DROP TABLE app.employees;

--changeset mmichalenok:4
CREATE TABLE IF NOT EXISTS app.doctors
(
    workhours integer,
    id bigint GENERATED BY DEFAULT AS IDENTITY  ,
    CONSTRAINT doctors_pkey PRIMARY KEY (id),
    CONSTRAINT id FOREIGN KEY (id)
        REFERENCES app.employees (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
--rollback DROP TABLE app.doctors;

--changeset mmichalenok:5

CREATE TABLE IF NOT EXISTS app.nurses
(
    blockcode VARCHAR(20) NOT NULL,
    blockfloor VARCHAR(20) NOT NULL,
    position VARCHAR(20) NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY  ,
    CONSTRAINT nurses_pkey PRIMARY KEY (id),
    CONSTRAINT id FOREIGN KEY (id)
        REFERENCES app.employees (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
--rollback DROP TABLE app.nurses;

--changeset mmichalenok:6

CREATE TABLE IF NOT EXISTS app.medical_histories
(
    id bigint GENERATED BY DEFAULT AS IDENTITY  ,
    diagnosis VARCHAR(100) NOT NULL,
    treatment VARCHAR(500) NOT NULL,
    dt_created timestamp without time zone NOT NULL,
    dt_updated timestamp without time zone NOT NULL,
    doctor_id bigint,
    patient_id bigint,
    CONSTRAINT medical_history_pkey PRIMARY KEY (id),
    CONSTRAINT id_doctor FOREIGN KEY (doctor_id)
        REFERENCES app.doctors (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT id_patient FOREIGN KEY (patient_id)
        REFERENCES app.patients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

--rollback DROP TABLE app.medical_histories;

--changeset mmichalenok:7
CREATE INDEX  IF NOT EXISTS doctors_workhours_index
ON app.doctors (workHours);

