debug: true
spring:
  jpa:
    properties:
      hibernate. dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: pass
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true